import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  profileCard: {
    width: "100%",
    padding: 24,
    gap: 24,
    borderWidth: 1,
    borderColor: "#C4C6CF",
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    shadowColor: "#000000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  profileHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 24,
  },
  profileAvatar: {
    width: 64,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#F7F9FB",
    backgroundColor: "#D6E3FF",
  },
  profileAvatarText: {
    color: "#002147",
    fontSize: 28,
    fontWeight: "700",
  },
  profileIdentity: {
    flex: 1,
    gap: 4,
  },
  name: {
    color: "#000A1E",
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "700",
  },
  statusBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: "#E7F5ED",
  },
  statusText: {
    color: "#1D7A42",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    letterSpacing: 0,
  },
  separator: {
    height: 1,
    backgroundColor: "#E0E3E5",
  },
  fields: {
    gap: 18,
  },
  fullField: {
    gap: 4,
  },
  splitRow: {
    flexDirection: "row",
    gap: 12,
  },
  splitField: {
    flex: 1,
    gap: 4,
  },
  label: {
    color: "#44474E",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    letterSpacing: 0,
  },
  valueBox: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 13,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(196,198,207,0.3)",
    backgroundColor: "#F2F4F6",
  },
  valueBoxCompact: {
    minHeight: 50,
    justifyContent: "center",
    paddingHorizontal: 13,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(196,198,207,0.3)",
    backgroundColor: "#F2F4F6",
  },
  valueBoxBetween: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingHorizontal: 13,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(196,198,207,0.3)",
    backgroundColor: "#F2F4F6",
  },
  valueText: {
    flexShrink: 1,
    color: "#191C1E",
    fontSize: 16,
    lineHeight: 24,
  },
  strongValue: {
    color: "#191C1E",
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "700",
  },
  floorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  floorText: {
    color: "#44474E",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  footer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingTop: 4,
  },
  footerText: {
    color: "#74777F",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    letterSpacing: 0,
  },
});

