import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  profileCard: {
    minHeight: 82,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
  },
  studentName: {
    color: "#191C1E",
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "700",
  },
  studentId: {
    marginTop: 4,
    color: "#44474E",
    fontSize: 14,
    lineHeight: 20,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#002147",
    borderWidth: 1,
    borderColor: "#C4C6CF",
  },
  avatarText: {
    color: "#708AB5",
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "700",
  },
  qrCard: {
    minHeight: 368,
    overflow: "hidden",
  },
  approvedBanner: {
    height: 29,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DCFCE7",
    borderBottomWidth: 1,
    borderBottomColor: "#BBF7D0",
  },
  approvedText: {
    color: "#166534",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    letterSpacing: 0,
  },
  qrBody: {
    alignItems: "center",
    gap: 16,
    paddingTop: 28,
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  qrCaption: {
    color: "#505F76",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    letterSpacing: 1.2,
  },
  qrFrame: {
    width: 212,
    height: 212,
    padding: 10,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: "#C4C6CF",
    backgroundColor: "#FFFFFF",
  },
  qrImage: {
    width: "100%",
    height: "100%",
  },
  validBadge: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: "#ECEEF0",
  },
  validBadgeText: {
    color: "#44474E",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  detailsGrid: {
    width: "100%",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#C4C6CF",
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
  },
  detailsTopRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#C4C6CF",
  },
  detailCell: {
    flex: 1,
    gap: 4,
    padding: 16,
  },
  detailCellBorder: {
    borderLeftWidth: 1,
    borderLeftColor: "#C4C6CF",
  },
  validityCell: {
    gap: 4,
    padding: 16,
    backgroundColor: "#F7F9FB",
  },
  detailLabel: {
    color: "#44474E",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    letterSpacing: 0,
  },
  detailValue: {
    color: "#191C1E",
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "700",
  },
  actionRow: {
    flexDirection: "row",
    gap: 16,
    paddingTop: 8,
  },
  secondaryButton: {
    flex: 1,
    height: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#74777F",
    borderRadius: 4,
    backgroundColor: "#FFFFFF",
  },
  primaryButton: {
    flex: 1,
    height: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 4,
    backgroundColor: "#000A1E",
  },
  secondaryButtonText: {
    color: "#000A1E",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    letterSpacing: 0,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    letterSpacing: 0,
  },
  buttonPressed: {
    opacity: 0.75,
  },
});

