import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#E8ECF2",
  },
  shell: {
    flex: 1,
    maxWidth: 430,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: "rgba(196,198,207,0.35)",
  },
  loginPanel: {
    width: "100%",
    maxWidth: 337,
    minHeight: 460,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: 28,
    paddingHorizontal: 54,
    backgroundColor: "#FFFFFF",
  },
  logo: {
    width: 76,
    height: 80,
  },
  headingBlock: {
    alignItems: "center",
    marginTop: 22,
  },
  title: {
    color: "#080A12",
    fontSize: 24,
    lineHeight: 31,
    fontWeight: "800",
    textAlign: "center",
    letterSpacing: 0,
  },
  subtitle: {
    marginTop: 2,
    color: "#44474E",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
    letterSpacing: 0,
  },
  form: {
    width: "100%",
    marginTop: 26,
    gap: 20,
  },
  fieldGroup: {
    width: "100%",
    gap: 8,
  },
  passwordLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  label: {
    color: "#191C1E",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    letterSpacing: 0,
  },
  forgotText: {
    color: "#191C1E",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    letterSpacing: 0,
  },
  inputWrap: {
    height: 40,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#C4C6CF",
    borderRadius: 4,
    backgroundColor: "#F7F9FB",
    overflow: "hidden",
  },
  inputIcon: {
    marginLeft: 10,
    marginRight: 8,
  },
  input: {
    flex: 1,
    height: "100%",
    paddingVertical: 0,
    paddingRight: 12,
    color: "#191C1E",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
  },
  signInButton: {
    height: 35,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    borderRadius: 4,
    backgroundColor: "#002147",
  },
  signInText: {
    color: "#FFFFFF",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    letterSpacing: 0,
  },
  buttonPressed: {
    opacity: 0.76,
  },
});

