import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  warningCard: {
    width: "100%",
    minHeight: 178,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(186,26,26,0.2)",
    backgroundColor: "rgba(255,218,214,0.2)",
  },
  warningIcon: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    borderRadius: 12,
    backgroundColor: "#FFDAD6",
  },
  warningTitle: {
    color: "#191C1E",
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "800",
    textAlign: "center",
  },
  warningCopy: {
    marginTop: 4,
    color: "#44474E",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  summaryCard: {
    width: "100%",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#C4C6CF",
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    shadowColor: "#002147",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  summaryHeader: {
    minHeight: 47,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    backgroundColor: "#000A1E",
  },
  summaryHeaderText: {
    color: "#FFFFFF",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    letterSpacing: 0,
  },
  checkedBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 2,
    backgroundColor: "#E8F5E9",
  },
  checkedText: {
    color: "#2E7D32",
    fontSize: 10,
    lineHeight: 15,
    fontWeight: "800",
    letterSpacing: 0,
  },
  summaryBody: {
    padding: 20,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#C4C6CF",
  },
  summaryColumn: {
    flex: 1,
    gap: 4,
  },
  summaryColumnRight: {
    flex: 1.05,
    alignItems: "flex-end",
    gap: 4,
  },
  summaryLabel: {
    color: "#74777F",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    letterSpacing: 0,
  },
  summaryValue: {
    color: "#191C1E",
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "700",
  },
  summaryValueRight: {
    color: "#191C1E",
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "700",
    textAlign: "right",
  },
  appliedRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingTop: 17,
  },
  appliedText: {
    color: "#44474E",
    fontSize: 14,
    lineHeight: 20,
  },
  actions: {
    gap: 12,
  },
  primaryButton: {
    width: "100%",
    height: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 8,
    backgroundColor: "#002147",
  },
  disabledButton: {
    width: "100%",
    height: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 8,
    opacity: 0.6,
    backgroundColor: "#ECEEF0",
  },
  primaryButtonText: {
    color: "#708AB5",
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "700",
  },
  disabledButtonText: {
    color: "#74777F",
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "700",
  },
  buttonPressed: {
    opacity: 0.75,
  },
});

